name: 'default'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  readiness:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        name: 'Setup node'
        with:
          node-version: '16.x'

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Test'
        run: yarn test --ci

      - name: 'Parse example'
        run: yarn build:all && yarn parse
